### ISSUE TITLE
Older versions of Android miss -U argument in pm list packages

### ISSUE THREAD

**Issue by noprey21** [mvt-project/mvt#211] opened 2021-10-28 10:16 UTC
Hi
Tried mvt-android download-apks on phone
but result:
```
NFO     [mvt.android.download_apks] Retrieving list of installed      
                  packages...                                                   
11:51:17 INFO     [mvt.android.download_apks] Extracted at total of 0 installed 
                  package names                                                 
11:51:18 INFO     [mvt.android.download_apks] Starting extraction of installed  
                  APKs at folder xxxxxxxx                              
         INFO     [mvt.android.download_apks] Selected only 0 packages which are
                  not marked as system                                          
         INFO     [mvt.android.download_apks] No packages were selected for     
                  download            
```
although apks are certainly installed and works OK with other phones

( this is a suspicious phone, almost certain)
best regards

**Comment by chlorophyll-zz** [comment] 2021-11-06 04:20
I have the same error. Even with "--all-apks".

> mvt-android download-apks --all-apks --all-checks --output ./apk/
> 
> 
>         MVT - Mobile Verification Toolkit
>                 https://mvt.re
>                 Version: 1.2.14
> 
> 
> 05:17:08 INFO     [mvt.android.download_apks] Retrieving list of installed packages...                                                                                                                
> 05:17:14 INFO     [mvt.android.download_apks] Extracted at total of 0 installed package names                                                                                                         
>          INFO     [mvt.android.download_apks] Starting extraction of installed APKs at folder ./apk/                                                                                                  
>          INFO     [mvt.android.download_apks] Selected all 0 available packages                                                                                                                       
>          INFO     [mvt.android.download_apks] No packages were selected for download

**Comment by botherder** [comment] 2021-11-06 13:49
If you run the command `adb shell pm list packages` what happens?
Does check-adb work?

**Comment by chlorophyll-zz** [comment] 2021-11-06 14:18
`adb shell pm list packages`
puts out a list of installed packages names (works)

`mvt-android check-adb`

> mvt-android check-adb
> 
> 
>         MVT - Mobile Verification Toolkit
>                 https://mvt.re
>                 Version: 1.2.14
> 
> 
> 15:15:03 INFO     [mvt.android.cli] Checking Android through adb bridge                                                                                                                               
>          INFO     [mvt.android.cli] Loaded a total of 0 indicators                                                                                                                                    
>          INFO     [mvt.android.modules.adb.chrome_history] Running module ChromeHistory...                                                                                                            
> 15:15:04 ERROR    [mvt.android.modules.adb.chrome_history] Error in running extraction from module ChromeHistory: 'function' object is not subscriptable                                              
>                   Traceback (most recent call last):                                                                                                                                                  
>                     File "/home/user/.local/lib/python3.9/site-packages/mvt/common/module.py", line 152, in run_module                                                                              
>                       module.run()                                                                                                                                                                    
>                     File "/home/user/.local/lib/python3.9/site-packages/mvt/android/modules/adb/chrome_history.py", line 80, in run                                                                 
>                       self._adb_process_file(os.path.join("/", CHROME_HISTORY_PATH),                                                                                                                  
>                     File "/home/user/.local/lib/python3.9/site-packages/mvt/android/modules/adb/base.py", line 232, in _adb_process_file                                                            
>                       process_routine(local_path)                                                                                                                                                     
>                     File "/home/user/.local/lib/python3.9/site-packages/mvt/android/modules/adb/chrome_history.py", line 70, in _parse_db                                                           
>                       "isodate": convert_timestamp_to_iso(convert_chrometime_to_unix[item[3]]),                                                                                                       
>                   TypeError: 'function' object is not subscriptable                                                                                                                                   
>          INFO     [mvt.android.modules.adb.sms] Running module SMS...                                                                                                                                 
> 15:15:05 ERROR    [mvt.android.modules.adb.sms] Error in running extraction from module SMS: expected string or bytes-like object                                                                     
>                   Traceback (most recent call last):                                                                                                                                                  
>                     File "/home/user/.local/lib/python3.9/site-packages/mvt/common/module.py", line 152, in run_module                                                                              
>                       module.run()                                                                                                                                                                    
>                     File "/home/user/.local/lib/python3.9/site-packages/mvt/android/modules/adb/sms.py", line 109, in run                                                                           
>                       self._adb_process_file(os.path.join("/", SMS_BUGLE_PATH), self._parse_db)                                                                                                       
>                     File "/home/user/.local/lib/python3.9/site-packages/mvt/android/modules/adb/base.py", line 232, in _adb_process_file                                                            
>                       process_routine(local_path)                                                                                                                                                     
>                     File "/home/user/.local/lib/python3.9/site-packages/mvt/android/modules/adb/sms.py", line 98, in _parse_db                                                                      
>                       if check_for_links(message["text"]) or message["text"].strip() == "":                                                                                                           
>                     File "/home/user/.local/lib/python3.9/site-packages/mvt/common/utils.py", line 75, in check_for_links                                                                           
>                       return re.findall("(?P<url>https?://[^\s]+)", text, re.IGNORECASE)                                                                                                              
>                     File "/usr/lib/python3.9/re.py", line 241, in findall                                                                                                                             
>                       return _compile(pattern, flags).findall(string)                                                                                                                                 
>                   TypeError: expected string or bytes-like object                                                                                                                                     
>          INFO     [mvt.android.modules.adb.whatsapp] Running module Whatsapp...                                                                                                                       
> 15:15:17 INFO     [mvt.android.modules.adb.whatsapp] Extracted a total of 281 WhatsApp messages containing links                                                                                      
>          INFO     [mvt.android.modules.adb.processes] Running module Processes...                                                                                                                     
>          INFO     [mvt.android.modules.adb.processes] Extracted records on a total of 0 processes                                                                                                     
>          INFO     [mvt.android.modules.adb.processes] The Processes module does not support checking for indicators                                                                                   
>          INFO     [mvt.android.modules.adb.dumpsys_batterystats] Running module DumpsysBatterystats...                                                                                                
> 15:15:18 INFO     [mvt.android.modules.adb.dumpsys_batterystats] The DumpsysBatterystats module does not support checking for indicators                                                              
>          INFO     [mvt.android.modules.adb.dumpsys_procstats] Running module DumpsysProcstats...                                                                                                      
> 15:15:20 INFO     [mvt.android.modules.adb.dumpsys_procstats] The DumpsysProcstats module does not support checking for indicators                                                                    
>          INFO     [mvt.android.modules.adb.dumpsys_packages] Running module DumpsysPackages...                                                                                                        
> 15:15:25 INFO     [mvt.android.modules.adb.dumpsys_packages] The DumpsysPackages module does not support checking for indicators                                                                      
>          INFO     [mvt.android.modules.adb.dumpsys_receivers] Running module DumpsysReceivers...                                                                                                      
> 15:15:29 INFO     [mvt.android.modules.adb.dumpsys_receivers] Found a receiver monitoring telephony state: "org.lineageos.recorder/.RecorderActivity"                                                 
> 15:15:30 INFO     [mvt.android.modules.adb.dumpsys_receivers] Found a receiver monitoring telephony state: "org.telegram.messenger/.CallReceiver"                                                     
>          INFO     [mvt.android.modules.adb.dumpsys_receivers] Found a receiver monitoring telephony state: "com.mc.miband1/.receiver.CallReceiver"                                                    
>          INFO     [mvt.android.modules.adb.dumpsys_receivers] Found a receiver monitoring telephony state: "com.android.deskclock/.alarms.PhoneStateReceiver"                                         
>          INFO     [mvt.android.modules.adb.dumpsys_receivers] Found a receiver to intercept incoming SMS messages: "org.thoughtcrime.securesms/.service.SmsListener"                                  
>          INFO     [mvt.android.modules.adb.dumpsys_receivers] Found a receiver to intercept incoming SMS messages: "com.mc.miband1/.receiver.SmsListener"                                             
>          INFO     [mvt.android.modules.adb.dumpsys_receivers] Found a receiver to intercept incoming SMS messages: "com.android.messaging/.receiver.SmsReceiver"                                      
>          INFO     [mvt.android.modules.adb.dumpsys_receivers] Found a receiver to intercept incoming SMS messages: "com.android.messaging/.receiver.AbortSmsReceiver"                                 
>          INFO     [mvt.android.modules.adb.dumpsys_receivers] Found a receiver to intercept incoming SMS messages: "com.google.android.apps.messaging/.shared.receiver.ConfigSmsReceiver"             
>          INFO     [mvt.android.modules.adb.dumpsys_receivers] Found a receiver to intercept incoming SMS messages: "com.google.android.apps.messaging/.shared.receiver.SmsReceiver"                   
>          INFO     [mvt.android.modules.adb.dumpsys_receivers] Found a receiver to intercept incoming SMS messages: "com.google.android.talk/com.google.android.apps.hangouts.sms.SmsReceiver"         
>          INFO     [mvt.android.modules.adb.dumpsys_receivers] The DumpsysReceivers module does not support checking for indicators                                                                    
>          INFO     [mvt.android.modules.adb.dumpsys_full] Running module DumpsysFull...                                                                                                                
> 15:16:09 INFO     [mvt.android.modules.adb.dumpsys_full] The DumpsysFull module does not support checking for indicators                                                                              
>          INFO     [mvt.android.modules.adb.packages] Running module Packages...                                                                                                                       
> 15:16:16 INFO     [mvt.android.modules.adb.packages] Extracted at total of 0 installed package names                                                                                                  
>          INFO     [mvt.android.modules.adb.rootbinaries] Running module RootBinaries...                                                                                                               
>          WARNING  [mvt.android.modules.adb.rootbinaries] Found root binary "su"                                                                                                                       
> 15:16:17 WARNING  [mvt.android.modules.adb.rootbinaries] Found root binary "magisk"                                                                                                                   
>          WARNING  [mvt.android.modules.adb.rootbinaries] Found root binary "magiskhide"                                                                                                               
>          WARNING  [mvt.android.modules.adb.rootbinaries] Found root binary "magiskinit"                                                                                                               
>          WARNING  [mvt.android.modules.adb.rootbinaries] Found root binary "magiskpolicy"                                                                                                             
>          INFO     [mvt.android.modules.adb.rootbinaries] The RootBinaries module does not support checking for indicators                                                                             
>          INFO     [mvt.android.modules.adb.logcat] Running module Logcat...                                                                                                                           
> 15:16:18 INFO     [mvt.android.modules.adb.logcat] The Logcat module does not support checking for indicators                                                                                         
>          INFO     [mvt.android.modules.adb.files] Running module Files...                                                                                                                             
> 15:16:35 INFO     [mvt.android.modules.adb.files] The Files module does not support checking for indicators

**Comment by noprey21** [comment] 2021-12-13 12:06
hi,
I have same results as chlorophyll-zz.
are there other stix files other than pegasus.stix (do not think pegasus is involved too expensive)
But someone is able to read with me on whatsap (even on different phones)
best regards

**Comment by chlorophyll-zz** [comment] 2021-12-13 14:10
@noprey21 OT: have you checked "Devices" in WhatsApp Settings for anyone having WhatApp Web access?

**Comment by orhun** [comment] 2021-12-30 15:35
Having the same issue here:

```sh
(orhun λ ~/mvt_results) mvt-android download-apks -a --output apks/ 


        MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 1.4.1


18:33:22 INFO     [mvt.android.download_apks] Retrieving list of installed packages...                                                                                                            
18:33:24 INFO     [mvt.android.download_apks] Extracted at total of 0 installed package names                                                                                                     
         INFO     [mvt.android.download_apks] Starting extraction of installed APKs at folder apks/                                                                                               
         INFO     [mvt.android.download_apks] Selected all 0 available packages                                                                                                                   
         INFO     [mvt.android.download_apks] No packages were selected for download 
```

ADB works as expected:

```sh
(orhun λ ~/mvt_results) adb shell pm list packages
* daemon not running; starting now at tcp:5037
* daemon started successfully
package:com.google.android.youtube
package:com.sec.android.app.camera
package:com.android.bluetooth
...
```

**Comment by kpcyrd** [comment] 2021-12-30 19:49
The exact command that's executed is

https://github.com/mvt-project/mvt/blob/512f40dcb458036f4ff4b89d5ab99b171803ff73/mvt/android/modules/adb/packages.py#L97

can you try running `adb shell pm list packages -U -u -i -f` and share some of the output (if there's any)?

**Comment by orhun** [comment] 2021-12-30 20:10
> adb shell pm list packages -U -u -i -f

```sh
(orhun λ ~) adb shell pm list packages -U -u -i -f
Error: Unknown option: -U
```

As you might've guessed magically, I'm using [android-tools](https://archlinux.org/packages/community/x86_64/android-tools/) (`31.0.3-2`) from the Arch Linux repositories. I'm not sure if it is relevant.

The phone I'm testing is Android 5.1 (API level 22).

**Comment by orhun** [comment] 2021-12-30 20:21
Hmm, looking at the `adb` documentation, I couldn't see what `-U` stands for:

![Screenshot 2021-12-30 at 23-20-18 Android Debug Bridge (adb) Android Developers](https://user-images.githubusercontent.com/24392180/147785559-cc9757f8-624d-4a75-a94f-d195303753bd.png)

https://developer.android.com/studio/command-line/adb#pm

**Comment by chlorophyll-zz** [comment] 2021-12-30 20:44
> > adb shell pm list packages -U -u -i -f

```
adb shell pm list packages -U -u -i -f
Error: Unknown option: -U
```

```
adb shell pm list packages -u -i -f
package:/system/priv-app/[package].apk=[package]  installer=null
(all packages following)
```

**Comment by kpcyrd** [comment] 2021-12-30 20:46
adb shell sends `"pm list packages -U -u -i -f"` as a string to the phone, the phone then passes it to `sh -c` and executes the `pm` binary on that device, so the phone may or may not have support for `-U`. The command did work on my test device (Android 11, Linage 18.1).

On my device it seems to enable the `uid` field:

```
% adb shell pm list packages -U -u -i -f | head -1
package:/data/app/~~0aX7BWdP29TqZaPPXkHNIA==/org.jitsi.meet-hcYO-DrfCgXIZKdu4pcUeA==/base.apk=org.jitsi.meet  installer=com.android.packageinstaller uid:10152
% adb shell pm list packages -u -i -f | head -1   
package:/data/app/~~0aX7BWdP29TqZaPPXkHNIA==/org.jitsi.meet-hcYO-DrfCgXIZKdu4pcUeA==/base.apk=org.jitsi.meet  installer=com.android.packageinstaller
% 
```




Android fragmentation strikes again. :headstone:

**Comment by chlorophyll-zz** [comment] 2021-12-30 21:11
```
grep -ir "pm list packages"
mvt/android/modules/adb/packages.py:        packages = self._adb_command("pm list packages -U -u -i -f")
mvt/android/modules/adb/packages.py:            output = self._adb_command(f"pm list packages {cmd['arg']}")
```

when I change "pm list packages -U -u -i -f" to "pm list packages -u -i -f" in mvt/android/modules/adb/packages.py, 
and then do in mvt folder
```
sudo pip uninstall mvt
sudo pip install .
mvt-android check-adb
```
the package scan now runs:
`INFO     [mvt.android.modules.adb.packages] Running module Packages
`Thanks @kpcyrd

**Comment by orhun** [comment] 2021-12-30 21:41
> when I change `pm list packages -U -u -i -f` to `pm list packages -u -i -f` in `mvt/android/modules/adb/packages.py` and then do in mvt folder

I can confirm that this also works for me.

Maybe there should be a fallback mechanism in case the `-U` flag fails? e.g. run with `-u -i -f` if `-U -u -i -f` returns "Error: Unknown option: -U"

**Comment by wtoalabi** [comment] 2022-01-06 16:28
https://www.codedruns.com/escort/Keylah
https://www.codedruns.com/escort/ELLA%20THICK
https://www.codedruns.com/escort/Kikky
https://www.codedruns.com/escort/Oluwatosin
https://www.codedruns.com/escort/Milk%20factory
https://www.codedruns.com/escort/Faithyfaithy
https://www.codedruns.com/escort/Niffycrown
https://www.codedruns.com/escort/Qwinbee
https://www.codedruns.com/escort/Vandy
https://www.codedruns.com/escort/Esyyy
https://www.codedruns.com/escort/Wetcandy
https://www.codedruns.com/escort/Crowngift
https://www.codedruns.com/escort/honeyberry

**Comment by botherder** [comment] 2022-01-21 11:21
I have tried to add a fix catching this issue. Can you test from the git repo?
e.g. `python3 dev/mvt-android check-adb -m Packages`

**Comment by chlorophyll-zz** [comment] 2022-01-21 13:30
Package inspection works now, thanks @botherder. @noprey21 You can close this issue.

```
sudo pip uninstall mvt
pip uninstall mvt
git clone https://github.com/mvt-project/mvt
cd mvt
sudo pip install .
mvt-android check-adb


        MVT - Mobile Verification Toolkit
                https://mvt.re
                Version: 1.4.5


[snip]                                  
         INFO     [mvt.android.modules.adb.packages] Running module Packages...
14:23:16 INFO     [mvt.android.modules.adb.packages] Found non-system package with name "[xxxxx]" installed by                
                  "com.android.vending" on [xxxxx]

[all non-system packages following]

         INFO     [mvt.android.modules.adb.packages] Extracted at total of 168 installed package names
[snip]
```

**Comment by botherder** [comment] 2022-01-21 15:28
Thanks.

**Closed as completed by botherder** 2022-01-21 15:28 UTC
Labels: bug

**Comment by mamaoi** [comment] 2022-02-08 22:21
Hi, is there someone who can help me maybe ? ... got same issue as above, removed all previous installed app but now when I try to install by the folder i get error like :
`Collecting appdirs>=1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
ERROR: Could not find a version that satisfies the requirement iOSbackup>=0.9.921 (from mvt) (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.9, 0.9.901, 0.9.902, 0.9.903, 0.9.904, 0.9.910, 0.9.912, 0.9.913)
ERROR: No matching distribution found for iOSbackup>=0.9.921
`
any help !! thanks

**Comment by chlorophyll-zz** [comment] 2022-02-12 04:07
@mamaoi please try to install from pip with `pip install mvt` or do a clean checkout in a new folder, then `cd mvt` and `pip install .`

**Comment by botherder** [comment] 2022-02-12 20:27
> Hi, is there someone who can help me maybe ? ... got same issue as above, removed all previous installed app but now when I try to install by the folder i get error like :
> 
> > 
> 
> ```
> Collecting appdirs>=1.4.4
> Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
> ERROR: Could not find a version that satisfies the requirement iOSbackup>=0.9.921 (from mvt) (from versions: 0.9.0, 0.9.1, 0.9.2, 0.9.9, 0.9.901, 0.9.902, 0.9.903, 0.9.904, 0.9.910, 0.9.912, 0.9.913)
> ERROR: No matching distribution found for `iOSbackup>=0.9.921
> ```
> 
> any help !! thanks

As mentioned in a separate issue, iOSbackup now requires Python >=3.8. You are almost certainly using a <=3.7. Unfortunately I'm afraid the only solution is to upgrade your Python version.

**Comment by telecran-telecrit** [comment] 2024-08-07 06:35
Yes, older **pm list packages -U | grep com.aefyr.sai** does not support "-U" and "--uid" options. 

Alternative command to know "uuid" by app package name is like: **dumpsys package | grep -B2 userId | grep -A2 com.aefyr.sai** 

P. S. : com.aefyr.sai is package name in example, sorry for not escaping dots. Google move me here, when I need to known uuid by name.
