### ISSUE TITLE
MVT not extracting any content from com.apple.osanalytics.addaily?

### ISSUE THREAD

**Issue by fibrizho** [mvt-project/mvt#339] opened 2023-04-14 12:08 UTC
Hi there,

I have realized that multiple times, MVT detects the file  but is unable to extract any content. For instance:
```

INFO     [mvt.ios.modules.mixed.osanalytics_addaily] Found com.apple.osanalytics.addaily plist at path:                                 
                  /home/user/mscan_reports/iphone/decrypted/f6/f65b5fafc69bbd3c60be019c6e938e146825fa83
INFO     [mvt.ios.modules.mixed.osanalytics_addaily] Extracted a total of 0 com.apple.osanalytics.addaily entries                       
INFO     [mvt.ios.modules.mixed.osanalytics_addaily] The OSAnalyticsADDaily module produced no detections!       
```

However, the plist file in Cellebrite shows a significant amount of content, although the file seems to be in hex. Not sure if this is a bug or I am missing something.

**Comment by Te-k** [comment] 2023-04-14 15:19
Hi, thanks for providing feedback. Do you know what kind of entries are identified by Cellebrite? Would you be able to share a plist file where there is such issue? (privately if it is easier, you can email me at tek AT randhome.io )

**Comment by fibrizho** [comment] 2023-04-17 13:28
Sure, will send it to you in private.

**Comment by Te-k** [comment] 2023-10-30 11:57
I couldn't reproduce this bug. Could you try again with the latest MVT version?

**Comment by fibrizho** [comment] 2023-10-30 12:02
Hi Étienne, indeed we cannot reproduce it anymore ourselves either :)

**Comment by Te-k** [comment] 2023-10-30 12:24
I am going to close it for now, but feel free to reopen if you have this issue again.

**Closed by Te-k** 2023-10-30 12:24 UTC
Labels: bug, ios
