### ISSUE TITLE
LIBUSB_ERROR_OTHER error launching mvt-android check-adb

### ISSUE THREAD

**Issue by kontys** [mvt-project/mvt#239] opened 2022-01-24 21:14 UTC
Hi! when i try mvt-adroid gives the following:
```
Traceback (most recent call last):
  File "/home/kontys/.local/bin/mvt-android", line 5, in <module>
    from mvt.android import cli
  File "/home/kontys/.local/lib/python3.8/site-packages/mvt/android/__init__.py", line 6, in <module>
    from .cli import cli
  File "/home/kontys/.local/lib/python3.8/site-packages/mvt/android/cli.py", line 19, in <module>
    from .download_apks import DownloadAPKs
  File "/home/kontys/.local/lib/python3.8/site-packages/mvt/android/download_apks.py", line 14, in <module>
    from .modules.adb.base import AndroidExtraction
  File "/home/kontys/.local/lib/python3.8/site-packages/mvt/android/modules/adb/__init__.py", line 6, in <module>
    from .chrome_history import ChromeHistory
  File "/home/kontys/.local/lib/python3.8/site-packages/mvt/android/modules/adb/chrome_history.py", line 13, in <module>
    from .base import AndroidExtraction
  File "/home/kontys/.local/lib/python3.8/site-packages/mvt/android/modules/adb/base.py", line 14, in <module>
    from adb_shell.adb_device import AdbDeviceTcp, AdbDeviceUsb
  File "/home/kontys/.local/lib/python3.8/site-packages/adb_shell/adb_device.py", line 86, in <module>
    from .transport.usb_transport import UsbTransport
  File "/home/kontys/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line 141, in <module>
    class UsbTransport(BaseTransport):   # pragma: no cover
  File "/home/kontys/.local/lib/python3.8/site-packages/adb_shell/transport/usb_transport.py", line 183, in UsbTransport
    USB1_CTX.open()
  File "/home/kontys/.local/lib/python3.8/site-packages/usb1/__init__.py", line 2177, in open
    mayRaiseUSBError(libusb1.libusb_init(byref(self.__context_p)))
  File "/home/kontys/.local/lib/python3.8/site-packages/usb1/__init__.py", line 128, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/home/kontys/.local/lib/python3.8/site-packages/usb1/__init__.py", line 120, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorOther: LIBUSB_ERROR_OTHER [-99]
```

**Comment by Te-k** [comment] 2022-01-26 14:31
Hi, this seems like an installation issue. Have you installed `libusb-1.0-0 sqlite3`? Does adb works to access the phone?

**Comment by lvlte** [comment] 2022-03-11 20:55
Hi, I got this issue when running `mvt-android` commands from WSL2 on Windows 10. 

Still, adb works (or seems to), running `adb devices` properly shows my device attached both on windows and WSL.

I got the exact same version of `platform-tools` installed for both :
```
>adb version
Android Debug Bridge version 1.0.41
Version 33.0.0-8141338
```

`libusb-1.0-0 sqlite3` correctly installed, Python 3.8.10. 

Any ideas ?

**Comment by Te-k** [comment] 2022-03-15 11:13
Can you access the phone using `adb shell`? Have you done `adb kill-server` before launching mvt?

**Comment by lvlte** [comment] 2022-03-17 13:05
@Te-k yes I can run `adb shell` commands. 

About `adb kill-server`, just to be sure we have the same understanding (or correct me if I'm wrong) : adb daemon must run on the windows side for adb (clients) to work both in windows and WSL, whereas if not running or if it runs in wsl, devices won't be detected. So, killing adb server just before launching mvt will actually prevent it to access the device, because mvt won't be able to start the daemon outside of wsl. 

That said, I don't think the issue is related because it persists with exactly the same error whatever the status of the daemon.

**Comment by talkahe** [comment] 2022-05-02 15:38
Same error here using WSL and adb over WiFi. I also can run shell.
Android Debug Bridge version 1.0.41
Version 33.0.1-8253317

**Comment by Te-k** [comment] 2022-06-17 08:54
I guess it is a problem specific to Windows then. MVT [is not officially supported on Windows](https://docs.mvt.re/en/latest/install/), we are happy to take PRs and update docs if there are some easy fixes but won't have capacity to debug that.

**Comment by botherder** [comment] 2022-10-15 09:04
Closing this as it's an issue we can't resolve ourselves. This is dependent on adb_shell, and there's an open ticket about it [here](https://github.com/JeffLIrion/adb_shell/issues/118). For Windows users, I would suggest using adb over WiFi as explained [here](https://docs.mvt.re/en/latest/android/adb/).

**Closed by botherder** 2022-10-15 09:04 UTC
Labels: android
