### ISSUE TITLE
Error in running extraction from module Files: not enough values to unpack (expected 6, got 1)

### ISSUE THREAD

**Issue by bashman** [mvt-project/mvt#268] opened 2022-05-06 21:03 UTC
![image](https://user-images.githubusercontent.com/1690516/167215957-87956828-7dce-4d3f-a32b-c6e51cffd3c8.png)

Android, POCO MIUI 13.03 
python 3.9 (anaconda)
mvt installed from pip (1.5.4)

**Comment by Te-k** [comment] 2022-05-25 13:37
Could you share privately (at tek [AT] randhome.io) what the following commands give in adb ?

```
find '/data/local/tmp/' -printf '%T@ %m %s %u %g %p\n' 2> /dev/null
find '/sdcard/' -printf '%T@ %m %s %u %g %p\n' 2> /dev/null
find '/tmp/' -printf '%T@ %m %s %u %g %p\n' 2> /dev/null
```

**Comment by bandisast** [comment] 2022-08-28 09:16
Can confirm as well:

```
Looking up 458 files... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
         INFO     [mvt.android.modules.adb.packages] Extracted at total of 486  
                  installed package names                                       
12:08:41 INFO     [mvt.android.modules.adb.packages] The Packages module        
                  produced no detections!                                       
12:08:42 INFO     [mvt.android.modules.adb.logcat] Running module Logcat...     
12:08:47 INFO     [mvt.android.modules.adb.logcat] Current logcat logs stored at
                  /home/username/Desktop/res3/logcat.txt                           
         INFO     [mvt.android.modules.adb.logcat] Logcat logs prior to last    
                  reboot stored at /home/username/Desktop/res3/logcat_last.txt     
         INFO     [mvt.android.modules.adb.logcat] The Logcat module does not   
                  support checking for indicators                               
         INFO     [mvt.android.modules.adb.root_binaries] Running module        
                  RootBinaries...                                               
12:08:48 INFO     [mvt.android.modules.adb.root_binaries] The RootBinaries      
                  module does not support checking for indicators               
         INFO     [mvt.android.modules.adb.files] Running module Files...       
12:08:57 ERROR    [mvt.android.modules.adb.files] Error in running extraction   
                  from module Files: not enough values to unpack (expected 6,   
                  got 1)                                                        
                  Traceback (most recent call last):                            
                    File                                                        
                  "/home/username/.local/lib/python3.9/site-packages/mvt/common/mod
                  ule.py", line 166, in run_module                              
                      module.run()                                              
                    File                                                        
                  "/home/username/.local/lib/python3.9/site-packages/mvt/android/mo
                  dules/adb/files.py", line 124, in run                         
                      self.find_files(media_folder)                             
                    File                                                        
                  "/home/username/.local/lib/python3.9/site-packages/mvt/android/mo
                  dules/adb/files.py", line 87, in find_files                   
                      [unix_timestamp, mode, size,                              
                  ValueError: not enough values to unpack (expected 6, got 1)  
```

Furthermore, only /tmp/ returns any output - the commands with /data/local/tmp and /sdcard/ do not return any output.

LMDE 5
Latest ADB downloaded from google's website
Android 12 SKQ1.210908.001, MIUI 13.0.10 Global
Xiaomi Redmi Note 10 Pro
Python 3.9.2
MVT 2.1.5

P.S.: I do not use English as the phone's language

**Comment by Manamama** [comment] 2022-10-23 18:27
Quick comments:
1. Yours may be a non-standard Android edition. Try running 
`adb shell cat /proc/version`
and update it here, after some basic anonymizing? 

2. FYI, out of these three commands only this one: 
`find '/tmp/' -printf '%T@ %m %s %u %g %p\n' 2> /dev/null`
does **not** show any files on my Droid, which is no wonder as:
```
ls /tmp/                                                                                                                                                      
ls: /tmp/: No such file or directory
```
3. FYI, yours is: 
`MVT 2.1.5, via pip `
while the current one is:
```
pip3 install --upgrade mvt ... 
mvt-android version 
-> ... Version: 2.2
```
Try upgrading - it may help.

**Comment by bandisast** [comment] 2022-10-24 11:25
Result with MVT 2.2: 

```
14:12:34 ERROR    [mvt.android.modules.adb.files] Error in running extraction   
                  from module Files: not enough values to unpack (expected 6,   
                  got 1)                                                        
                  Traceback (most recent call last):                            
                    File                                                        
                  "/home/user/.local/lib/python3.9/site-packages/mvt/common/mod
                  ule.py", line 166, in run_module                              
                      module.run()                                              
                    File                                                        
                  "/home/user/.local/lib/python3.9/site-packages/mvt/android/mo
                  dules/adb/files.py", line 124, in run                         
                      self.find_files(media_folder)                             
                    File                                                        
                  "/home/user/.local/lib/python3.9/site-packages/mvt/android/mo
                  dules/adb/files.py", line 87, in find_files                   
                      [unix_timestamp, mode, size,                              
                  ValueError: not enough values to unpack (expected 6, got 1) 
```

Result of `adb shell cat /proc/version`:
```
Linux version 4.14.190-perf-gd1f5180ae73c (clang version 10.0.7 for Android NDK, GNU ld (binutils-2.27-bd24d23f) 2.27.0.20170315) #1 SMP PREEMPT Wed Aug 10 19:37:40 CST 2022
```

Small correction on my part when it comes to the previous post, I probably accidentally ran the commands without adb. On the adb shell (today), the directory /data/local/tmp/ is empty; the directory /tmp/ does not exist, And of course the /sdcard/ directory shows all my files. Apologies for the confusion above.


Android Debug Bridge version 1.0.41 Version 28.0.2-debian
Python 3.9.2

**Comment by Manamama** [comment] 2022-10-25 08:34
Thank you. I am not a Python developer or maintainer of this tool, so quick informal advice:

1. Your Android (phone) is newer than mine (flashed Lineage): 
`Linux version 3.18.124-perf-g9100df495471-dirty `
but then your clang is older, cf mine:
`clang version 12.0.6`
I doubt that it affects anything because:
2. This sample page explains this error https://www.delftstack.com/howto/python/not-enough-values-to-unpack/ in more detail.
3. My tip would be to run it in any debugger (Pycharm etc.) and check what exactly is this discrepancy between the expected number of arguments (values) and the ones fed in, as per the URL above:
```
A ValueError is a common exception in Python that occurs when the number of values doesn’t match the number of variables either taking input, direct assignment or through an array or accessing restricted values. To understand the ValueError, let’s take an example:
# this input statement expects three values as input
x,y,z = input("Enter values for x, y and z: ").split(",")
Output:
Enter values for x, y and z: 1,2
ValueError: not enough values to unpack (expected 3, got 2)
```
Alas, I cannot give you more help - the maintainers should know the root causes much better. 
Good luck!

**Comment by Te-k** [comment] 2022-10-29 17:13
Hi,
Could you share the first 10 lines of `find '/data/media/0' -type f -printf '%T@ %m %s %u %g %p\n' 2> /dev/null` and `find '/sdcard/' -type f -printf '%T@ %m %s %u %g %p\n' 2> /dev/null`? (Either here or by email to tek AT randhome.io)

Thanks

**Comment by itsintavis** [comment] 2022-12-07 22:10
I have the same problem. The output is as follows:

         INFO     [mvt.android.modules.adb.files] Running module Files...       
23:53:16 ERROR    [mvt.android.modules.adb.files] Error in running extraction   
                  from module Files: not enough values to unpack (expected 6,   
                  got 1)                                                        
                  Traceback (most recent call last):                            
                    File                                                        
                  "/Library/Frameworks/Python.framework/Versions/3.11/lib/python
                  3.11/site-packages/mvt/common/module.py", line 166, in        
                  run_module                                                    
                      module.run()                                              
                    File                                                        
                  "/Library/Frameworks/Python.framework/Versions/3.11/lib/python
                  3.11/site-packages/mvt/android/modules/adb/files.py", line    
                  124, in run                                                   
                      self.find_files(media_folder)                             
                    File                                                        
                  "/Library/Frameworks/Python.framework/Versions/3.11/lib/python
                  3.11/site-packages/mvt/android/modules/adb/files.py", line 87,
                  in find_files                                                 
                      [unix_timestamp, mode, size,                              
                  ValueError: not enough values to unpack (expected 6, got 1)

**Comment by itsintavis** [comment] 2022-12-08 11:18
Will test also and revert

**Comment by itsintavis** [comment] 2022-12-09 15:55
Problem persists after upgrade to Android 13.

![IMG20221209175508.jpg](https://user-images.githubusercontent.com/4021662/206741501-f501dea8-dc64-410b-a796-33278f7fd22b.jpg)

**Comment by accesocero** [comment] 2022-12-09 17:31
Instalamos : pip3 install –user mvt

mvt-android check-adb

Crea una carpeta en tu sistema

**Comment by accesocero** [comment] 2022-12-09 17:35
mvt-android download-apks –output /home/garba/nombrecarpeta–all-checks

**Comment by SahraLibre** [comment] 2022-12-17 21:37
not sure how to use this

**Comment by bandisast** [comment] 2022-12-18 09:33
I believe I have found the/an culprit in my case. @Te-k 

So, I added a `print()` statement in `mvt/android/modules/adb/files.py` such that:

```python
    def find_files(self, folder: str) -> None:
        if self.full_find:
            cmd = f"find '{folder}' -type f -printf '%T@ %m %s %u %g %p\n' 2> /dev/null"
            output = self._adb_command(cmd)

            if output.strip() == "":
                return

            for file_line in output.splitlines():
                print(file_line) #<-- here
                [unix_timestamp, mode, size,
                 owner, group, full_path] = file_line.rstrip().split(" ", 5)
                mod_time = convert_unix_to_iso(unix_timestamp)
```

Which would print every file up to the point of the crash. I have found that the culprit in this case was at:

`1647250715.651322768 660 184632 u0_a294 sdcard_rw /sdcard/Android/data/gr.winbank.mobilenext/files/Documents/winbank mobile - TRANSACTION DETAILS`
`.pdf`
 which is a transaction receipt from my bank.

Then, I ran the `find` command manually via ADB and:
`1647250715.651322768 660 184632 u0_a294 sdcard_rw /sdcard/Android/data/gr.winbank.mobilenext/files/Documents/winbank mobile - TRANSACTION DETAILS`
`.pdf`

It seems that the bank was inserting a special character (`\n` ?) after the filename and before the file suffix (.pdf). So, MVT was parsing `.pdf` as a separate file. Obviously, there are no arguments on date, UNIX permissions, owners, etc about that file on *that* line. As such, the error was `ValueError: not enough values to unpack (expected 6, got 1)`

I then browsed to that path using ADB and ran `ls`:
`-rw-rw---- 1 u0_a294 sdcard_rw 184632 2022-03-14 11:38 winbank\ mobile\ -\ TRANSACTION\ DETAILS\n.pdf`

Then I deleted both the file and the folder using ADB (as the folder's contents weren't accessible via my file browser) and ran `mvt-android check-adb` again.

```
1670679156.660784672 660 0 root everybody /sdcard/.fe_tmp
11:31:30 INFO     [mvt.android.modules.adb.files] Found 56312 files in primary  
                  Android tmp and media folders                                 
         INFO     [mvt.android.modules.adb.files] Processing full file listing. 
                  This may take a while...                                      
```

And it worked!
So, it seems that the culprit is stray `\n` characters in filenames.
I can think of several ways to counteract this issue, but I'll leave it up to you to decide which is the optimal solution.

**Comment by Te-k** [comment] 2022-12-20 17:53
This is great, thank you so much! 
I don't see any very clean way to manage that, maybe the easiest would be to skip lines that aren't in the right format. I don't see any easy way to identify is a misformated line is the end of a file name or something else, so I'm not sure I want to try reconstructing file names.

**Comment by bandisast** [comment] 2022-12-21 07:46
To avoid abuse (e.g. hiding malware in files with `\n` and other special characters), whenever a line is skipped, I'd recommend printing the content of the line being skipped + the content of the previous line. E.g.:

```python
[WARNING]: Skipping line ".pdf", previous line:
"1647250715.651322768 660 184632 u0_a294 sdcard_rw /sdcard/Android/data/gr.winbank.mobilenext/files/Documents/winbank mobile - TRANSACTION DETAILS" 
due to incorrect formatting. Renaming the file might fix this issue.
```

It might not be a perfect solution, but it's probably a good-enough solution

**Comment by Te-k** [comment] 2023-02-08 19:04
Hi, I just fixed that in the repository. The code will be part of MVT 2.2.2 that should be on pypi soon. Let me know if you still encounter that issue.

**Closed** 2023-02-08 19:03 UTC
Labels: bug, android
