### ISSUE TITLE
help backup spyapps

### ISSUE THREAD

**Issue by donso98** [mvt-project/mvt#540] opened 2024-09-26 15:15 UTC
Hi, I have done check-backup on my iPhone backup after suspicious actions, can anyone interpret the result? Should I run other commands besides check-backup?

INFO     [mvt.ios.cmd_check_backup] Loaded a total of 9979 unique indicators
         INFO     [mvt] Checking iTunes backup located at: 00008110-0004752C0E12401E
         INFO     [mvt.ios.modules.backup.backup_info] Running module BackupInfo...
         INFO     [mvt.ios.modules.backup.backup_info] Build Version: 20F75
         INFO     [mvt.ios.modules.backup.backup_info] Device Name: iPhone di Sanfi
         INFO     [mvt.ios.modules.backup.backup_info] Display Name: iPhone di Sanfi
         INFO     [mvt.ios.modules.backup.backup_info] GUID: 0FA60BF8E9E19FFFABAE204A8A14AF8C
         INFO     [mvt.ios.modules.backup.backup_info] ICCID: None
         INFO     [mvt.ios.modules.backup.backup_info] IMEI: 350302395244540
         INFO     [mvt.ios.modules.backup.backup_info] MEID: 35030239524454
         INFO     [mvt.ios.modules.backup.backup_info] Installed Applications: ['com.lcfld.fldpublic',
                  'com.facebook.Messenger', 'com.amazon.Lassen', 'com.amazon.AmazonUK', 'com.procwise.Procwise',
                  'com.lcfld.spaceseries', 'com.yahoo.Aerogram', 'com.facebook.Facebook', '8K2NU5962N',
                  'com.google.ios.youtube', 'com.serendipit.DeviceMonitor', 'com.bitdefender.iossecurity',
                  'com.shix.camthe', 'com.lcfld.trbfpv', 'com.dh.audio.voicerecorder.VoiceRecorderV3',
                  'com.sielte.MySielteID', 'net.whatsapp.WhatsApp', 'com.kaspersky.securityadvisor',
                  'com.burbn.instagram', 'it.sielte.sielteidentify', 'com.mobidia.My-Data-Mgr', 'com.subito.subito',
                  'com.vodafone.my190', 'com.google.GoogleMobile', 'com.herinechin.colormyfrenchie', 'com.google.Gmail']
         INFO     [mvt.ios.modules.backup.backup_info] Last Backup Date: 2024-09-20 23:18:01
         INFO     [mvt.ios.modules.backup.backup_info] Phone Number: None
         INFO     [mvt.ios.modules.backup.backup_info] Product Name: iPhone 13 Pro
         INFO     [mvt.ios.modules.backup.backup_info] Product Type: iPhone14,2 (iPhone 13 Pro)
         INFO     [mvt.ios.modules.backup.backup_info] Product Version: 16.5.1
         INFO     [mvt.ios.modules.backup.backup_info] Serial Number: F3DQKQC6XF
         INFO     [mvt.ios.modules.backup.backup_info] Target Identifier: 00008110-0004752C0E12401E
         INFO     [mvt.ios.modules.backup.backup_info] Target Type: Device
         INFO     [mvt.ios.modules.backup.backup_info] Unique Identifier: 00008110-0004752C0E12401E
         INFO     [mvt.ios.modules.backup.backup_info] iTunes Version: 12.13.3.2
         WARNING  [mvt.ios.modules.backup.backup_info] This phone is running an outdated iOS version: 16.5.1 (latest is
                  18)
         INFO     [mvt.ios.modules.backup.backup_info] The BackupInfo module does not support checking for indicators
         INFO     [mvt.ios.modules.backup.configuration_profiles] Running module ConfigurationProfiles...
14:04:53 INFO     [mvt.ios.modules.backup.configuration_profiles] Extracted details about 0 configuration profiles
         INFO     [mvt.ios.modules.backup.configuration_profiles] The ConfigurationProfiles module produced no
                  detections!
         INFO     [mvt.ios.modules.backup.manifest] Running module Manifest...
         INFO     [mvt.ios.modules.backup.manifest] Found Manifest.db database at path:
                  00008110-0004752C0E12401E/Manifest.db
^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A14:05:11 INFO     [mvt.ios.modules.backup.manifest] Extracted a total of 198415 file metadata items
14:05:22 INFO     [mvt.ios.modules.backup.manifest] The Manifest module produced no detections!
14:05:25 INFO     [mvt.ios.modules.backup.profile_events] Running module ProfileEvents...
         INFO     [mvt.ios.modules.backup.profile_events] Extracted 0 profile events
         INFO     [mvt.ios.modules.backup.profile_events] The ProfileEvents module produced no detections!
         INFO     [mvt.ios.modules.mixed.calls] Running module Calls...
         INFO     [mvt.ios.modules.mixed.calls] There might be no data to extract by module Calls: unable to find the
                  module's database file
         INFO     [mvt.ios.modules.mixed.chrome_favicon] Running module ChromeFavicon...
         INFO     [mvt.ios.modules.mixed.chrome_favicon] There might be no data to extract by module ChromeFavicon:
                  unable to find the module's database file
         INFO     [mvt.ios.modules.mixed.chrome_history] Running module ChromeHistory...
         INFO     [mvt.ios.modules.mixed.chrome_history] There might be no data to extract by module ChromeHistory:
                  unable to find the module's database file
         INFO     [mvt.ios.modules.mixed.contacts] Running module Contacts...
         INFO     [mvt.ios.modules.mixed.contacts] Found Contacts database at path:
                  00008110-0004752C0E12401E/31/31bb7ba8914766d4ba40d6dfb6113c8b614be442
         INFO     [mvt.ios.modules.mixed.contacts] Extracted a total of 928 contacts from the address book
         INFO     [mvt.ios.modules.mixed.contacts] The Contacts module does not support checking for indicators
         INFO     [mvt.ios.modules.mixed.firefox_favicon] Running module FirefoxFavicon...
         INFO     [mvt.ios.modules.mixed.firefox_favicon] There might be no data to extract by module FirefoxFavicon:
                  unable to find the module's database file
         INFO     [mvt.ios.modules.mixed.firefox_history] Running module FirefoxHistory...
         INFO     [mvt.ios.modules.mixed.firefox_history] There might be no data to extract by module FirefoxHistory:
                  unable to find the module's database file
         INFO     [mvt.ios.modules.mixed.idstatuscache] Running module IDStatusCache...
         INFO     [mvt.ios.modules.mixed.idstatuscache] Found IDStatusCache plist at path:
                  00008110-0004752C0E12401E/6b/6b97989189901ceaa4e5be9b7f05fb584120e27b
         INFO     [mvt.ios.modules.mixed.idstatuscache] Extracted a total of 0 ID Status Cache entries
         INFO     [mvt.ios.modules.mixed.idstatuscache] The IDStatusCache module produced no detections!
         INFO     [mvt.ios.modules.mixed.interactionc] Running module InteractionC...
         INFO     [mvt.ios.modules.mixed.interactionc] There might be no data to extract by module InteractionC: unable
                  to find the module's database file
         INFO     [mvt.ios.modules.mixed.locationd] Running module LocationdClients...
         INFO     [mvt.ios.modules.mixed.locationd] Found Locationd Clients plist at path:
                  00008110-0004752C0E12401E/a6/a690d7769cce8904ca2b67320b107c8fe5f79412
         INFO     [mvt.ios.modules.mixed.locationd] Extracted a total of 80 Locationd Clients entries
         INFO     [mvt.ios.modules.mixed.locationd] The LocationdClients module produced no detections!
         INFO     [mvt.ios.modules.mixed.osanalytics_addaily] Running module OSAnalyticsADDaily...
         INFO     [mvt.ios.modules.mixed.osanalytics_addaily] Found com.apple.osanalytics.addaily plist at path:
                  00008110-0004752C0E12401E/f6/f65b5fafc69bbd3c60be019c6e938e146825fa83
         INFO     [mvt.ios.modules.mixed.osanalytics_addaily] Extracted a total of 214 com.apple.osanalytics.addaily
                  entries between 2022-06-15 12:55:34 and 2024-09-19 19:20:39
         INFO     [mvt.ios.modules.mixed.osanalytics_addaily] The OSAnalyticsADDaily module produced no detections!
         INFO     [mvt.ios.modules.mixed.net_datausage] Running module Datausage...
         INFO     [mvt.ios.modules.mixed.net_datausage] Found DataUsage database at path:
                  00008110-0004752C0E12401E/0d/0d609c54856a9bb2d56729df1d68f2958a88426b
         INFO     [mvt.ios.modules.mixed.net_datausage] Extracted information on 2296 processes
         INFO     [mvt.ios.modules.mixed.net_datausage] The Datausage module produced no detections!
         INFO     [mvt.ios.modules.mixed.safari_browserstate] Running module SafariBrowserState...
         INFO     [mvt.ios.modules.mixed.safari_browserstate] Extracted a total of 0 tab records and 0 session history
                  entries
         INFO     [mvt.ios.modules.mixed.safari_browserstate] The SafariBrowserState module produced no detections!
         INFO     [mvt.ios.modules.mixed.safari_history] Running module SafariHistory...
         INFO     [mvt.ios.modules.mixed.safari_history] Extracted a total of 0 history records
         INFO     [mvt.ios.modules.mixed.safari_history] The SafariHistory module produced no detections!
         INFO     [mvt.ios.modules.mixed.tcc] Running module TCC...
         INFO     [mvt.ios.modules.mixed.tcc] Found TCC database at path:
                  00008110-0004752C0E12401E/64/64d0019cb3d46bfc8cce545a8ba54b93e7ea9347
         INFO     [mvt.ios.modules.mixed.tcc] Found client "net.whatsapp.WhatsApp" with access allowed to microphone on
                  2022-02-03 21:32:53.000000 by system_set
         INFO     [mvt.ios.modules.mixed.tcc] Found client "net.whatsapp.WhatsApp" with access allowed to camera on
                  2022-02-04 10:47:25.000000 by user_consent
         INFO     [mvt.ios.modules.mixed.tcc] Found client "com.facebook.Messenger" with access allowed to camera on
                  2022-02-06 20:26:10.000000 by user_consent
         INFO     [mvt.ios.modules.mixed.tcc] Found client "com.facebook.Messenger" with access allowed to microphone on
                  2022-02-06 20:26:14.000000 by user_consent
         INFO     [mvt.ios.modules.mixed.tcc] Found client "com.burbn.instagram" with access allowed to camera on
                  2023-07-31 15:11:48.000000 by user_consent
         INFO     [mvt.ios.modules.mixed.tcc] Found client "com.burbn.instagram" with access allowed to microphone on
                  2023-07-31 15:11:49.000000 by user_consent
         INFO     [mvt.ios.modules.mixed.tcc] Found client "com.facebook.Facebook" with access allowed to camera on
                  2023-11-27 20:55:53.000000 by system_set
         INFO     [mvt.ios.modules.mixed.tcc] Found client "com.facebook.Facebook" with access allowed to microphone on
                  2024-05-18 07:32:13.000000 by user_consent
         INFO     [mvt.ios.modules.mixed.tcc] Found client "com.shix.camthe" with access allowed to camera on 2024-09-17
                  11:43:11.000000 by user_consent
         INFO     [mvt.ios.modules.mixed.tcc] Found client "com.google.GoogleMobile" with access allowed to microphone
                  on 2024-09-18 23:35:50.000000 by user_consent
         INFO     [mvt.ios.modules.mixed.tcc] Extracted a total of 125 TCC items
         INFO     [mvt.ios.modules.mixed.tcc] The TCC module produced no detections!
         INFO     [mvt.ios.modules.mixed.sms] Running module SMS...
         INFO     [mvt.ios.modules.mixed.sms] Found SMS database at path:
                  00008110-0004752C0E12401E/3d/3d0d7e5fb2ce288813306e4d4636395e047a3d28
         INFO     [mvt.ios.modules.mixed.sms] Extracted a total of 500 SMS messages
14:05:28 INFO     [mvt.ios.modules.mixed.sms] The SMS module produced no detections!
         INFO     [mvt.ios.modules.mixed.sms_attachments] Running module SMSAttachments...
         INFO     [mvt.ios.modules.mixed.sms_attachments] Found SMS database at path:
                  00008110-0004752C0E12401E/3d/3d0d7e5fb2ce288813306e4d4636395e047a3d28
         INFO     [mvt.ios.modules.mixed.sms_attachments] Extracted a total of 17 SMS attachments
         INFO     [mvt.ios.modules.mixed.sms_attachments] The SMSAttachments module produced no detections!
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Running module WebkitResourceLoadStatistics...
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/7f/7f6840fe03ce4ce7d4fa56f1efa43d4caba4cfae
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/62/62bc511425c104baa2317c9148f82beb425538b4
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 52 records from
                  00008110-0004752C0E12401E/62/62bc511425c104baa2317c9148f82beb425538b4
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/48/48172b3fb8004dc6f02bf6ea6f3dc124c917bf5e
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 52 records from
                  00008110-0004752C0E12401E/48/48172b3fb8004dc6f02bf6ea6f3dc124c917bf5e
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/52/526edf8c8eaf166d4f4d7aa50a5d110f6013ddf2
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 96 records from
                  00008110-0004752C0E12401E/52/526edf8c8eaf166d4f4d7aa50a5d110f6013ddf2
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/c3/c381d47234662d09e0e818d563ddbe39a743f69d
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 132 records from
                  00008110-0004752C0E12401E/c3/c381d47234662d09e0e818d563ddbe39a743f69d
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/94/946c838869839807f4582a3243c3011af48559f6
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 132 records from
                  00008110-0004752C0E12401E/94/946c838869839807f4582a3243c3011af48559f6
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/2a/2a66e971eb3b4f00c2dbc0382a345ed3ff6653ce
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 346 records from
                  00008110-0004752C0E12401E/2a/2a66e971eb3b4f00c2dbc0382a345ed3ff6653ce
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/01/018a76cf728408de7f1fb6b98c1f6212e0ce7b14
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 346 records from
                  00008110-0004752C0E12401E/01/018a76cf728408de7f1fb6b98c1f6212e0ce7b14
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/f6/f653134757c17c495b1f2790714a4a41ce366883
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 1203 records from
                  00008110-0004752C0E12401E/f6/f653134757c17c495b1f2790714a4a41ce366883
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/97/97fefad2d44a46795ab0f33f76471b85d86e4c9d
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 1304 records from
                  00008110-0004752C0E12401E/97/97fefad2d44a46795ab0f33f76471b85d86e4c9d
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/d6/d64d82c9b6b18fc32a6004cb3c5f2684cb2744cb
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 1318 records from
                  00008110-0004752C0E12401E/d6/d64d82c9b6b18fc32a6004cb3c5f2684cb2744cb
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/56/56cfc7eafeeb1046d08bfeb2f462c90e13b7e8a2
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 1318 records from
                  00008110-0004752C0E12401E/56/56cfc7eafeeb1046d08bfeb2f462c90e13b7e8a2
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/ab/aba1a955c1dd593efb5a7f07d12865c410a62c4e
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 1324 records from
                  00008110-0004752C0E12401E/ab/aba1a955c1dd593efb5a7f07d12865c410a62c4e
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/25/253d2cfa0c5b8f430cc4fba1c309cced9d849389
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 1324 records from
                  00008110-0004752C0E12401E/25/253d2cfa0c5b8f430cc4fba1c309cced9d849389
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/1a/1a76196fe19eb6bc9d0bf68c5b4c56034c8eda7d
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 1324 records from
                  00008110-0004752C0E12401E/1a/1a76196fe19eb6bc9d0bf68c5b4c56034c8eda7d
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/92/92fc546c75df7c76985962b014560d8e13780869
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 1330 records from
                  00008110-0004752C0E12401E/92/92fc546c75df7c76985962b014560d8e13780869
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/9b/9ba907777442f4c3b0086c213b70a56cecd863db
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 1330 records from
                  00008110-0004752C0E12401E/9b/9ba907777442f4c3b0086c213b70a56cecd863db
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/a5/a55cee1a735cb9b994951757312af505bfd08066
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 1330 records from
                  00008110-0004752C0E12401E/a5/a55cee1a735cb9b994951757312af505bfd08066
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/05/05ec5948b25c523f32caf538a7d4243b817765bf
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 1416 records from
                  00008110-0004752C0E12401E/05/05ec5948b25c523f32caf538a7d4243b817765bf
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/c9/c94275875a1af065ae2b9100f90630a53acf1f69
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 1462 records from
                  00008110-0004752C0E12401E/c9/c94275875a1af065ae2b9100f90630a53acf1f69
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/b7/b7379a6d3494fdceb7e231da7b73bfa9a244900d
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 1462 records from
                  00008110-0004752C0E12401E/b7/b7379a6d3494fdceb7e231da7b73bfa9a244900d
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/b0/b095123fe7d67d2229f74bdc5bb227a952310ba1
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 2000 records from
                  00008110-0004752C0E12401E/b0/b095123fe7d67d2229f74bdc5bb227a952310ba1
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/8f/8fb9f16e90984904cd6eb0611c80dd242bcb07da
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 2000 records from
                  00008110-0004752C0E12401E/8f/8fb9f16e90984904cd6eb0611c80dd242bcb07da
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/29/29cfd982ab189c190c42fe4c4da5003257928111
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 2002 records from
                  00008110-0004752C0E12401E/29/29cfd982ab189c190c42fe4c4da5003257928111
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/49/49b6d9ff45c1b8336e4db93b0d444a8086c9e7bf
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 2002 records from
                  00008110-0004752C0E12401E/49/49b6d9ff45c1b8336e4db93b0d444a8086c9e7bf
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found WebKit ResourceLoadStatistics
                  observations.db file at path 00008110-0004752C0E12401E/44/44fd8591b339c1b2aee6a9bfa6134fc02cb4d3c5
         INFO     [mvt.ios.modules.mixed.webkit_resource_load_statistics] Extracted a total of 2002 records from
                  00008110-0004752C0E12401E/44/44fd8591b339c1b2aee6a9bfa6134fc02cb4d3c5

         WARNING  [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found a known suspicious domain
                  spappmonitoring.com matching indicator "spappmonitoring.com" from "EasyPhoneTrack"

         WARNING  [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found a known suspicious domain flexispy.com
                  matching indicator "flexispy.com" from "FlexiSpy"

         WARNING  [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found a known suspicious domain mspy.com
                  matching indicator "mspy.com" from "mSpy"

         WARNING  [mvt.ios.modules.mixed.webkit_resource_load_statistics] Found a known suspicious domain clevguard.com
                  matching indicator "clevguard.com" from "ClevGuard"

         INFO     [mvt.ios.modules.mixed.webkit_session_resource_log] Running module WebkitSessionResourceLog...
         INFO     [mvt.ios.modules.mixed.webkit_session_resource_log] Extracted records from 0 Safari browsing session
                  resource logs
         INFO     [mvt.ios.modules.mixed.webkit_session_resource_log] The WebkitSessionResourceLog module produced no
                  detections!
         INFO     [mvt.ios.modules.mixed.whatsapp] Running module Whatsapp...
         INFO     [mvt.ios.modules.mixed.whatsapp] Found WhatsApp database at path:
                  00008110-0004752C0E12401E/7c/7c7fba66680ef796b916b067077cc246adacf01d
14:05:31 INFO     [mvt.ios.modules.mixed.whatsapp] Extracted a total of 224245 WhatsApp messages
14:05:34 INFO     [mvt.ios.modules.mixed.whatsapp] The Whatsapp module produced no detections!
14:05:35 INFO     [mvt.ios.modules.mixed.shortcuts] Running module Shortcuts...
         INFO     [mvt.ios.modules.mixed.shortcuts] Found Shortcuts database at path:
                  00008110-0004752C0E12401E/5b/5b4d0b44b5990f62b9f4d34ad8dc382bf0b01094
14:05:36 INFO     [mvt.ios.modules.mixed.shortcuts] Extracted a total of 4 Shortcuts
         INFO     [mvt.ios.modules.mixed.shortcuts] The Shortcuts module produced no detections!
         INFO     [mvt.ios.modules.mixed.applications] Running module Applications...
         INFO     [mvt.ios.modules.mixed.applications] Extracted a total of 26 applications
         INFO     [mvt.ios.modules.mixed.applications] The Applications module produced no detections!
         INFO     [mvt.ios.modules.mixed.calendar] Running module Calendar...
         INFO     [mvt.ios.modules.mixed.calendar] Found calendar database at path:
                  00008110-0004752C0E12401E/20/2041457d5fe04d39d0ab481178355df6781e6858
         INFO     [mvt.ios.modules.mixed.calendar] Extracted a total of 28 calendar items
         INFO     [mvt.ios.modules.mixed.calendar] The Calendar module produced no detections!
         INFO     [mvt.ios.modules.mixed.global_preferences] Running module GlobalPreferences...
         INFO     [mvt.ios.modules.mixed.global_preferences] Found Global Preference database at path:
                  00008110-0004752C0E12401E/0d/0dc926a1810f7aee4e8f38793ed788701f93bf9d
         INFO     [mvt.ios.modules.mixed.global_preferences] Extracted a total of 19 Global Preferences
         INFO     [mvt.ios.modules.mixed.global_preferences] The GlobalPreferences module produced no detections!
         
WARNING   NOTE: Detected indicators of compromise. Only expert review can confirm if the detected indicators
                  are signs of an attack.

                  Please seek reputable expert help if you have serious concerns about a possible spyware attack. Such
                  support is available to human rights defenders and civil society through Amnesty International's
                  Security Lab at https://securitylab.amnesty.org/get-help/?c=mvt
         WARNING  [mvt] The analysis of the backup produced 4 detections

!

**Comment by DrWhax** [comment] 2024-09-26 21:21
Duplicate of #539

**Closed by DrWhax** 2024-09-26 21:21 UTC
